import puppeteer from 'puppeteer-core';
const b = await puppeteer.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', headless:'new', args:['--no-sandbox']});
const p = await b.newPage();
const errs=[]; p.on('pageerror',e=>errs.push(String(e)));
await p.emulateMediaFeatures([{name:'prefers-reduced-motion', value:'reduce'}]);
await p.setViewport({width:1440,height:900,deviceScaleFactor:2});
await p.goto('http://127.0.0.1:8899/', {waitUntil:'networkidle0'});
await new Promise(r=>setTimeout(r,1200));
const rows = await p.$$eval('tbody tr', r=>r.length);
const heads = await p.$$eval('thead th', h=>h.map(x=>x.innerText.trim().split('\n')[0]));
console.log('rows', rows, '| headers', JSON.stringify(heads));
console.log('pageerrors', errs.length ? errs : 'none');
await p.screenshot({path:'/private/tmp/claude-501/-Users-admin-Downloads-CODES-AGENTS-Agent-Smith/ddb1318a-40b9-4cbf-a67d-410203b14622/scratchpad/my-light.png'});
await p.emulateMediaFeatures([{name:'prefers-color-scheme', value:'dark'},{name:'prefers-reduced-motion', value:'reduce'}]);
await new Promise(r=>setTimeout(r,600));
await p.screenshot({path:'/private/tmp/claude-501/-Users-admin-Downloads-CODES-AGENTS-Agent-Smith/ddb1318a-40b9-4cbf-a67d-410203b14622/scratchpad/my-dark.png'});
const p2 = await b.newPage();
await p2.setViewport({width:390,height:844,deviceScaleFactor:2});
await p2.goto('http://127.0.0.1:8899/t/mai-transcribe-2.html', {waitUntil:'networkidle0'});
await new Promise(r=>setTimeout(r,800));
console.log('tool h1', await p2.$eval('h1', e=>e.innerText));
await p2.screenshot({path:'/private/tmp/claude-501/-Users-admin-Downloads-CODES-AGENTS-Agent-Smith/ddb1318a-40b9-4cbf-a67d-410203b14622/scratchpad/my-tool-390.png'});
await b.close();
