import puppeteer from "puppeteer-core";
const exe = process.argv[2];
const b = await puppeteer.launch({ executablePath: exe, headless: "new", args: ["--no-sandbox"] });
const p = await b.newPage();
let t0 = Date.now();
const r = await p.goto("https://fonts.googleapis.com/css2?family=Inter&display=swap", { timeout: 15000 }).catch(e => console.log("fonts:", e.message));
console.log("fonts status", r?.status(), Date.now() - t0);
t0 = Date.now();
const r2 = await p.goto("http://127.0.0.1:5199/assets/index-CRSXcRQt.css", { timeout: 15000 }).catch(e => console.log("css:", e.message));
console.log("css status", r2?.status(), Date.now() - t0);
await b.close();
