import puppeteer from "puppeteer-core";
const exe = process.argv[2];
const b = await puppeteer.launch({ executablePath: exe, headless: "new", args: ["--no-sandbox"] });
const p = await b.newPage();
p.on("request", r => console.log("req", r.url().slice(0,80)));
p.on("requestfailed", r => console.log("FAILED", r.url().slice(0,80), r.failure()?.errorText));
const t0 = Date.now();
await p.goto("http://127.0.0.1:5199/demo-tabel", { waitUntil: "networkidle2", timeout: 20000 }).catch(e => console.log("goto:", e.message));
console.log("loaded in", Date.now() - t0, "rows:", await p.$$eval("tbody tr", r => r.length).catch(e => e.message));
await b.close();
